### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by MagmaBro123** [justaureus/ReimagEND#10]
Title.

Terra-bukkit-6.2.1-BETA+358e09d05, Paper 1.19.2.

End has not changed.

![2022-12-14_14 30 22](https://user-images.githubusercontent.com/51277766/207718971-6554390b-efe0-4275-9fc8-e7f8b1e04f0f.png)

**Comment by justaureus** [comment]
You'll have to provide more information, I've tested this on Bukkit and it works as of today.  Please provide the logs and your bukkit.yml
