### ISSUE TITLE
End city gen bug

### ISSUE THREAD

**Issue by iRama7** [justaureus/ReimagEND#13]
Sometimes the cities in the end are cut off because they reach the maximum height (256)

**Comment by DeathShadez** [comment]
Any particular biome?

**Comment by iRama7** [comment]
All of the biomes where end cities can spawn

**Comment by DAYOREAM** [comment]
Too many end cities! I can't find a way to minish the spawn-chance

**Comment by DeathShadez** [comment]
Appreciate the additional feedback.

Pretty sure that most biomes use either the vanilla biomes end_highlands or end_midlands that spawn end cities.

Changing more of these biomes into end_barrens or small_end_islands should reduce the chances of them spawning.

**Comment by DeathShadez** [comment]
The default end biome terrain has been lowered, so end city cutoffs should be less likely along with setting certain biomes with weird end city spawns as `end_barrens` to prevent end city spawns in those biomes.
