### ISSUE TITLE
Problems via switching  to Only_End generation

### ISSUE THREAD

**Issue by YaAlekseyka** [justaureus/ReimagEND#20]
End looks like vanilla when I changed like this
![image](https://github.com/justaureus/ReimagEND/assets/151193788/4b9f14cc-fb53-41b0-9f0e-39e6a84e10de)

**Comment by DeathShadez** [comment]
I'm guessing you want to remove the Aether zone pockets?
You just need to comment out << biome-providers/stages/aether_pockets.yml:stages in stages: below

**Comment by DeathShadez** [comment]
Aether pocket generation can now be disabled by going to the `meta.yml` and toggling the toggle-aether-pockets value
