### ISSUE TITLE
Possibility to disable biomes

### ISSUE THREAD

**Issue by WarnDa** [justaureus/ReimagEND#21]
Hello,
I'll use this pack on a multiplayer server (yes even if it's beta) with 150 players online, but we saw the "void_sea" biome with full water and fear this could cause performance issue especially if the water start moving.

![image](https://github.com/justaureus/ReimagEND/assets/31826333/fdaf10aa-5c0d-42b0-8d62-16a263d92e5a)

It is planned to get a settings to disable some biomes ?

**Comment by DeathShadez** [comment]
https://github.com/justaureus/ReimagEND/blob/main/biome-providers/stages/void_distribution.yml
Go to this file and comment out void_sea at the bottom

**Comment by WarnDa** [comment]
> https://github.com/justaureus/ReimagEND/blob/main/biome-providers/stages/void_distribution.yml Go to this file and comment out void_sea at the bottom

Thanks a lot ! :D
